### ISSUE TITLE
Need better error reporting when .bai file is not present

### ISSUE THREAD

**Issue by tonydisera** [chmille4/bam.iobio.io#5] opened 2014-09-02 17:53 UTC
Need better error reporting when bai file is missing.  Right now, when loading the bam file from a URL, if the corresponding .bai file is not present, the failure is silent.  We should send an error message back to the web page that indicates that the corresponding .bai file is not found.  Down the road, it might me nice to generate a .bai file on the fly if it is not present.

**Comment by mjbowler** [comment] 2018-02-16 20:35
Duplicate of 75?

**Closed** 2018-03-26 20:03 UTC
Labels: enhancement, priority later
