### ISSUE TITLE
Force show entire autosome

### ISSUE THREAD

**Issue by mjbowler** [chmille4/bam.iobio.io#83] opened 2018-02-23 23:10 UTC

**Comment by AlistairNWard** [comment] 2018-05-15 20:12
For example, open this file:

https://s3.amazonaws.com/iobio/samples/bam/example_data/test.bam

There is no data for chromosome 6, but it isn't immediately clear since the chromosome is missing in the read coverage chart.

**Comment by anderspitman** [comment] 2018-08-15 23:08
@AlistairNWard just to confirm before I implement this, what we want to do is take any sequence references in the bam header which are never referenced in the alignment records, and explicitly show that there wasn't any data provided for those references?

I have confirmed that at least for the example file you shared, there is an SQ entry for chr6, but no read depth data is returned for it from the backend.

**Comment by AlistairNWard** [comment] 2018-08-16 12:43
Exactly. One of the main purposes of this Read Coverage chart is to see if there are any major file issues. This would include, for example, that an entire chromosome was missed. If a BAM file was truncated and we only have alignments up to chr17, we would still want to see chr18 up to chr22 in the chart, but with zero coverage, so the user quickly sees the problem. So with this example BAM, we would see a big gap in the coverage where chr6 should be.

**Comment by anderspitman** [comment] 2018-08-17 00:16
@AlistairNWard I have a kinda hacky solution in place. Basically if I detect any header SQs for which there haven't been any records, I insert a number of dumy 0-depth entries equal to the SQ length (LN). Here's what it looks like:

![screenshot_2018-08-16 bam iobio](https://user-images.githubusercontent.com/7820200/44241286-239a4a00-a180-11e8-8ea7-8695d493c105.png)

I'd prefer if we could actually show blank data in this case, or maybe even highlight a red zone or something. I'm currently trying to figure out what it would take to do that. I think it might require upstream changes to `iobio.viz`, specifically the multiLine chart. Before spending too much time on that, I wanted to check with you and get your input.

Also, I though @chmille4 might know if there's a way to accomplish this without changing iobio.viz.

**Comment by AlistairNWard** [comment] 2018-08-17 13:31
You can call it hacky, but right off the bat, this is a massive improvement. Instantly, I can see that chr6 is missing, and then there is no data for the sex chromosomes. Immediately useful!

**Comment by anderspitman** [comment] 2018-08-17 20:03
@AlistairNWard I'm able to achieve this result with fairly minimal changes to `iobio.viz`:

![screenshot_2018-08-17 bam iobio](https://user-images.githubusercontent.com/7820200/44285949-834a3100-a224-11e8-9580-81eb9ab9f4b2.png)

I think we have few options for moving forward, depending on our goals:

1. The simplest is to use my basic hack where we just show 0 coverage for missing data. The user receives no indication that this is any different than a read with 0 coverage. I accomplished this by inserting the values manually.

2. By making a small change to `iobio.viz`, I can remove the points for missing data. This makes it obvious that there is something different, but it still might not be clear what's wrong from the visualization.

3. With more work, I could introduce a "missing data" object type that when passed into `iobio.viz` could have custom behavior. For example showing a red background where data is missing. This would require more involved changes to iobio.viz, but would make the code in BamView.vue much more semantic and non-hacky, since instead of inserting dummy data we're telling it explicitly where data is missing.

For both of the first 2 cases (and maybe we'd want to for the 3rd anyway), we could add a popup or something to tell the user data is missing for certain SQs.

The reasons I'm hesitant to modify `iobio.viz` is because I'm not sure if the version we have included in the bam repo is up-to-date. If it's out of sync, updating to the latest could turn into a project of it's own. @chmille4 do you happen to know the status of that and how difficult I might expect rebuilding `iobio.viz` for bam to be?

**Comment by anderspitman** [comment] 2018-08-17 20:04
In my opinion, unless updating `iobio.viz` is trivial, we might as well do 3 if we want to do 2. If we just want a reasonable release ASAP then we can just do 1 (probably with a UI popup) and leave an issue to improve this later.

**Comment by anderspitman** [comment] 2018-08-22 19:49
Fixed in #104

**Closed by anderspitman** 2018-08-22 19:49 UTC
Labels: in progress
